Этап 2. Основной сервис
MrOlegBar/java-explore-with-me pull request #4
Opened 2023-05-05 12:26 UTC by MrOlegBar

2023-05-10 01:39 UTC, EvgenyKoptubenko commented on docker-compose.generated.override.yml
> +# This is a generated file. Not intended for manual editing.
Точно ли этот файл нужен?

2023-05-10 01:41 UTC, EvgenyKoptubenko commented on docker-compose.yml
> +      - "9091:9091"
Расскажи для чего каждый порт? Для чего 9090 и 9091 для одного сервиса?

2023-05-10 01:49 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/controller/privatee/EventPrivateController.java
> +    @PostMapping("/users/{userId}/events")
/users/{userId} можно вынести в общую часть в описание контроллера

2023-05-10 01:51 UTC, EvgenyKoptubenko commented
Если отправить неверный запрос, то приходит слишком длинное сообщение об ошибке
{
	"status": "BAD_REQUEST",
	"reason": "Email не соответствует формату электронной почты.",
	"message": "Email не соответствует формату электронной почты.",
	"errors": [
		"org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:141)",
		"org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)",
		"org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)",
		"org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)",
		"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)",
		"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)",
		"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)",
		"org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)",
		"org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964)",
		"org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)",
		"org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:696)",
		"org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)",
		"javax.servlet.http.HttpServlet.service(HttpServlet.java:779)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)",
		"org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)",
		"org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)",
		"org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)",
		"org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)",
		"org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)",
		"org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)",
		"org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)",
		"org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)",
		"org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)",
		"org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)",
		"org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)",
		"org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)",
		"org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)",
		"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)",
		"org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)",
		"org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)",
		"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)",
		"java.base/java.lang.Thread.run(Thread.java:829)"
	],
	"timestamp": "2023-05-10T01:50:43.446685"
}

2023-05-10 01:53 UTC, EvgenyKoptubenko commented
Если отправить такой запрос curl --request GET \
  --url http://localhost:8080/admin/users
То приходит 500
{
	"timestamp": "2023-05-10T01:52:42.361+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/admin/users"
}

2023-05-10 01:57 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/controller/publicc/EventPublicController.java
> +            eventService.save(event);
Попробуй заменить на saveAll, т.е. использовать батч вместо единичного обновления  https://www.baeldung.com/spring-data-jpa-batch-inserts

2023-05-10 01:59 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/practicum/error/ErrorHandler.java
> +        }
Код, который вытаскивает стек трейс дублируется из метода в метод
List<String> errors = new ArrayList<>();
        StackTraceElement[] stackTraceElements = e.getStackTrace();

        for (StackTraceElement error : stackTraceElements) {
            errors.add(error.toString());
        }

2023-05-10 02:01 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Проект гигантский и в нем довольно сложно найти ошибки с помощью код ревью. Есть базовые предложения по изменению кода

2023-05-10 08:46 UTC, MrOlegBar commented on docker-compose.generated.override.yml
> +# This is a generated file. Not intended for manual editing.
Если вопрос ставится таким образом - значит не нужен)

2023-05-10 08:49 UTC, MrOlegBar commented on docker-compose.yml
> +      - "9091:9091"
9090 для связи между основными модулями, а 9091 для "Remote JVM Debug"

2023-05-10 09:53 UTC, MrOlegBar commented
> http://localhost:8080/admin/users

Исправил.

2023-05-10 10:17 UTC, MrOlegBar commented on ewm-service/src/main/java/ru/practicum/controller/publicc/EventPublicController.java
> +            eventService.save(event);
Исправил.

2023-05-11 01:31 UTC, EvgenyKoptubenko approved these changes
Работа сделана очень хорошо. Спасибо.

2023-05-11 04:37 UTC, merged